services:
  - type: web
    name: hirecraft-ai
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: export PYTHONPATH=/opt/render/project/src/app:$PYTHONPATH && cd app && gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
